[package]
name = "shipwreck"
version = "0.0.1"
authors = ["ethanshry <ehshry@gmail.com>"]
edition = "2018"

[dependencies]
lapin-async = "^0.21"
serde = "1.0"
serde_derive = "1.0.92"
reqwest = "0.9.18"